export const ADD_REGION = 'ADD_REGION'
export const FETCH_LIST_SUCCESS = 'FETCH_LIST_SUCCESS'
export const SHOW_LOADER = 'SHOW_LOADER'
export const HIDE_LOADER = 'HIDE_LOADER'
export const SHOW_ALERT = 'SHOW_ALERT'
export const HIDE_ALERT = 'HIDE_ALERT'
